"""B2 — the OpenAI-compatible adapter (Contract B, spec/20).

One class for every provider that speaks OpenAI's `/v1/chat/completions`, which is all of them
except Anthropic: **Groq, OpenAI, xAI, DeepSeek, Mistral, OpenRouter** and **Google**'s compat
layer in the cloud, plus **Ollama, LM Studio and llama.cpp** locally. What differs between them
is a base URL and a credential, and both come from the catalogue
(`spec/schemas/settings.json`, hard rule 3) — so this is one adapter, not nine.

That is also why spec/20's B2 row was widened rather than a fourth row added (D30): "local
OpenAI-compatible server" and "cloud OpenAI-compatible API" were never two pieces of code.

    python -m bridge.brains.compat groq "what time is it in Tokyo?"   # live round-trip
    python -m bridge.brains.compat --selfcheck                        # no network
"""
from __future__ import annotations

import argparse
import asyncio
import json
import sys
from typing import Any, AsyncIterator

from .base import (
    DEFAULT_SYSTEM,
    MAX_TOKENS,
    Done,
    Error,
    Session,
    TextDelta,
    ToolCall,
    ToolSpec,
    ssl_context,
)
from .providers import base_url, card, credential_for

# OpenAI's client requires an Authorization header to exist even when the server ignores it,
# so a local runner (Ollama / LM Studio / llama.cpp) gets this rather than None.
LOCAL_PLACEHOLDER_KEY = "not-needed"


def _error_kind(exc: Exception) -> str:
    """Map an SDK exception to a shared Contract B Error kind (spec/20) by its TYPE and status
    code — never by matching the message prose (B-02).

    Same ladder as B1, and for the same reason: every provider here collapses context overflow
    and other bad requests into one 400, so a 400 maps to `unknown` (the generic apology)
    instead of a prose heuristic that mis-narrates. The OpenAI SDK's exception hierarchy is
    generated by the same tool as Anthropic's, so the shapes line up.
    """
    import openai

    if isinstance(exc, openai.AuthenticationError):
        return "auth"
    if isinstance(exc, openai.RateLimitError):
        return "rate_limit"
    if isinstance(exc, openai.APIConnectionError):
        # Covers a local runner that simply isn't running — the commonest local failure.
        return "unavailable"
    if isinstance(exc, openai.APIStatusError):
        return "unavailable" if exc.status_code >= 500 else "unknown"
    return "unknown"


def _tools_for_api(tools: list[ToolSpec]) -> list[dict]:
    """Contract T registry entries -> OpenAI function-tool objects.

    Translation lives in the adapter because it IS the provider's wire format, exactly like
    error mapping (spec/20). `spec/schemas/tools.json` spells the JSON-schema key `parameters`
    and carries a `tier` field, which is Gemma's safety business and not something to ship to
    a provider — so the registry entry is never passed through verbatim.
    """
    return [
        {
            "type": "function",
            "function": {
                "name": t["name"],
                "description": t.get("description", ""),
                "parameters": t.get("parameters") or {"type": "object", "properties": {}},
            },
        }
        for t in tools
    ]


class CompatBrain:
    """B2. `converse` is an async generator, matching the BrainAdapter Protocol."""

    def __init__(
        self,
        provider: str,
        model: str | None = None,
        api_key: str | None = None,
        endpoint: str | None = None,
        effort: str | None = None,
        temperature: float | None = None,
    ):
        self.provider = provider
        self.card = card(provider)
        self.local = self.card.get("where") == "local"
        self.base_url = base_url(provider, endpoint)
        # No default model, by design: the adapter privileges none, and a turn with no model
        # yields a clean Error below rather than silently picking the first of some list. The
        # picker (settings) and the router choose the model; this class just uses what it is given.
        self.model = model
        self._api_key = api_key or credential_for(provider) or (
            LOCAL_PLACEHOLDER_KEY if self.local else None
        )
        self.effort = effort
        self.temperature = temperature
        self._client = None          # built on first use, then kept — see _client_once()

    def _client_once(self):
        """One client for this adapter's life, resting on Contract B's one-loop guarantee
        (spec/20). Same two costs avoided as in B1: a fresh TCP+TLS handshake per turn, and
        ~190 ms of CPU re-reading this machine's CA bundle (`ssl_context()` memoises it).

        `DefaultAsyncHttpxClient`, NOT a bare `httpx.AsyncClient`: the SDK passes a supplied
        client through verbatim, and a bare one silently swaps the SDK's 600 s read timeout for
        httpx's 5 s default — which would kill exactly the slow-first-token turns this exists to
        speed up. B1 records the same trap; it is a property of the SDK generator, not of either
        provider.
        """
        import openai

        if self._client is None:
            self._client = openai.AsyncOpenAI(
                api_key=self._api_key,
                base_url=self.base_url,
                http_client=openai.DefaultAsyncHttpxClient(verify=ssl_context()),
            )
        return self._client

    def _kwargs(self, session: Session, utterance: str, tools: list[ToolSpec]) -> dict[str, Any]:
        # On this wire the system prompt is the first MESSAGE, not a separate parameter as it is
        # on Anthropic's. That is the whole message-shape difference between B1 and B2.
        messages: list[dict[str, Any]] = [
            {"role": "system", "content": session.system or DEFAULT_SYSTEM}
        ]
        messages += list(session.history)
        # An empty utterance is the tool-loop CONTINUE signal (spec/20): the tool results are
        # already in history (record_tool_round wrote them), so add no user turn.
        if utterance:
            messages.append({"role": "user", "content": utterance})

        kwargs: dict[str, Any] = dict(
            model=self.model,
            max_tokens=session.max_tokens or MAX_TOKENS,   # transform lifts this for long text
            messages=messages,
            stream=True,
        )
        if not self.local:
            # Local servers vary on whether they accept this and a rejection costs the whole
            # turn, so usage (a latency-log nicety) is asked for only where it is reliable.
            kwargs["stream_options"] = {"include_usage": True}
        if self.effort and (self.card.get("capabilities", {}) or {}).get("effort"):
            kwargs["reasoning_effort"] = self.effort
        # A per-call temperature (transform's determinism) overrides the adapter's own default.
        temperature = session.temperature if session.temperature is not None else self.temperature
        if temperature is not None:
            kwargs["temperature"] = temperature
        if tools:
            kwargs["tools"] = _tools_for_api(tools)
        return kwargs

    async def converse(
        self,
        session: Session,
        utterance: str,
        tools: list[ToolSpec],
    ) -> AsyncIterator:
        if session.local_only and not self.local:
            yield Error("unavailable", f"B2/{self.provider} blocked: session is local_only")
            return
        if not self.base_url:
            yield Error("unknown", f"no endpoint for {self.provider!r}")
            return
        if not self._api_key:
            cred = self.card.get("credential", self.provider)
            yield Error("auth", f"no API key (keyring service 'gemma', account {cred!r})")
            return
        if not self.model:
            yield Error("unknown", f"no model chosen for {self.provider!r}")
            return

        client = self._client_once()
        # index -> the call being assembled. This wire streams a tool call as FRAGMENTS: the id
        # and name arrive once, the arguments as a run of partial JSON strings that only parse
        # once concatenated. Anthropic hands over whole blocks instead, which is why B1 has no
        # equivalent of this bookkeeping.
        calls: dict[int, dict[str, str]] = {}
        usage: dict[str, int] | None = None

        try:
            stream = await client.chat.completions.create(**self._kwargs(session, utterance, tools))
            async for chunk in stream:
                if chunk.usage is not None:
                    usage = {
                        "input_tokens": chunk.usage.prompt_tokens,
                        "output_tokens": chunk.usage.completion_tokens,
                    }
                if not chunk.choices:
                    continue                      # the include_usage chunk carries no choices
                delta = chunk.choices[0].delta
                if delta is None:
                    continue
                if delta.content:
                    yield TextDelta(delta.content)
                for tc in delta.tool_calls or []:
                    slot = calls.setdefault(tc.index, {"id": "", "name": "", "args": ""})
                    if tc.id:
                        slot["id"] = tc.id
                    if tc.function is not None:
                        if tc.function.name:
                            slot["name"] = tc.function.name
                        if tc.function.arguments:
                            slot["args"] += tc.function.arguments

            for slot in calls.values():
                try:
                    parsed = json.loads(slot["args"] or "{}")
                except ValueError:
                    # The reserved kind, finally used: spec/20 anticipates exactly this on the
                    # OpenAI wire, where a small or local model can emit arguments that never
                    # parse. The retry spec/20 mentions belongs to the tool loop, not here.
                    yield Error(
                        "malformed_tool_call",
                        f"{slot['name'] or '?'} arguments are not JSON: {slot['args'][:200]!r}",
                    )
                    return
                yield ToolCall(slot["id"], slot["name"], parsed)
            yield Done(usage=usage)
        except Exception as exc:  # noqa: BLE001 - map every provider error to Error
            yield Error(_error_kind(exc), str(getattr(exc, "message", exc)))

    @staticmethod
    def record_tool_round(session: Session, assistant_text: str, calls, results: dict) -> None:
        """Append one completed tool round to `session.history` in OpenAI's wire shape, so the
        next converse round (driven with an empty utterance) sees the tool_calls and their results.
        Wire format, so it lives here like tool translation and error mapping; the orchestrator
        owns the loop and executes the tools (spec/20).

        `results` maps a tool_call id -> its result string. This wire wants ONE assistant message
        carrying the `tool_calls` array, then ONE `tool` message per result — the mirror of B1's
        single tool_result user message."""
        session.history.append({
            "role": "assistant",
            "content": assistant_text or None,
            "tool_calls": [
                {"id": c.id, "type": "function",
                 "function": {"name": c.name, "arguments": json.dumps(c.input)}}
                for c in calls
            ],
        })
        for c in calls:
            session.history.append(
                {"role": "tool", "tool_call_id": c.id, "content": results.get(c.id, "")})


async def _run(provider: str, question: str, model: str | None) -> int:
    brain = CompatBrain(provider, model=model)
    print(f"[{provider} -> {brain.base_url} model={brain.model}]", file=sys.stderr)
    status = 0
    async for ev in brain.converse(Session(id="cli"), question, []):
        if isinstance(ev, TextDelta):
            print(ev.text, end="", flush=True)
        elif isinstance(ev, ToolCall):
            print(f"\n[tool_call {ev.name} {ev.input}]", flush=True)
        elif isinstance(ev, Done):
            print(f"\n[done: {ev.usage}]")
        elif isinstance(ev, Error):
            print(f"\n[error/{ev.kind}: {ev.detail}]", file=sys.stderr)
            status = 1
    return status


def _selfcheck() -> None:
    # No network anywhere in here: every assertion is about request shaping, error mapping and
    # client lifetime. The one thing a live run adds is proof the provider agrees, which is what
    # `python -m bridge.brains.compat groq "..."` is for.
    import time

    import openai

    def _exc(cls, status=None):
        e = cls.__new__(cls)
        if status is not None:
            e.status_code = status
        return e

    # Error mapping is by exception TYPE and status code, never message prose (B-02).
    assert _error_kind(_exc(openai.AuthenticationError)) == "auth"
    assert _error_kind(_exc(openai.RateLimitError)) == "rate_limit"
    assert _error_kind(_exc(openai.APIConnectionError)) == "unavailable"
    assert _error_kind(_exc(openai.InternalServerError, 500)) == "unavailable"
    assert _error_kind(_exc(openai.BadRequestError, 400)) == "unknown", \
        "a 400 must map to the generic apology — no prose-guessing at 'context' (B-02)"
    assert _error_kind(_exc(openai.NotFoundError, 404)) == "unknown", "a bad model id is not a 5xx"
    assert _error_kind(RuntimeError("boom")) == "unknown"

    # Tool translation: the registry's OWN entries must survive it, since that is the shape the
    # brain will really be handed. `tier` is Gemma's business and must never reach a provider.
    from bridge.config import load_schemas

    registry = load_schemas()["tools"]["tools"]
    assert registry, "spec/schemas/tools.json must carry the starter tools"
    assert any("tier" in t for t in registry), "the registry is expected to carry tiers"
    wired = _tools_for_api(registry)
    assert len(wired) == len(registry)
    for w, t in zip(wired, registry):
        assert w["type"] == "function"
        assert w["function"]["name"] == t["name"]
        assert "tier" not in w and "tier" not in w["function"], "tier must not leave the machine"
        assert w["function"]["parameters"] == t["parameters"], \
            "the registry's `parameters` IS the JSON schema on this wire"
    assert _tools_for_api([{"name": "bare"}])[0]["function"]["parameters"] == \
        {"type": "object", "properties": {}}, "a tool with no parameters must still be valid JSON schema"

    # Request shaping. The system prompt is a MESSAGE here, not a parameter (the one real
    # difference from B1), and history must sit between it and the new utterance.
    groq = CompatBrain("groq", model="m", api_key="x")
    s = Session(id="t", history=[{"role": "user", "content": "before"},
                                {"role": "assistant", "content": "reply"}])
    k = groq._kwargs(s, "now", [])
    assert k["messages"][0]["role"] == "system" and k["messages"][0]["content"] == DEFAULT_SYSTEM
    assert [m["content"] for m in k["messages"][1:]] == ["before", "reply", "now"], k["messages"]
    assert k["stream"] is True, "adapters MUST stream (spec/20)"
    assert k["stream_options"] == {"include_usage": True}, "cloud turns should report usage"
    assert "tools" not in k, "no tools key at all when the list is empty"
    assert "reasoning_effort" not in k, "effort must not be sent unasked"
    assert groq._kwargs(Session(id="t", system="custom"), "q", [])["messages"][0]["content"] == \
        "custom", "a session system prompt must win over the default"

    # Tool-loop continue signal: an empty utterance adds NO user message (the tool results are
    # already in history), so two user turns never stack up.
    kc = groq._kwargs(Session(id="t", history=[{"role": "user", "content": "q"}]), "", [])
    assert [m["role"] for m in kc["messages"]] == ["system", "user"], kc["messages"]

    # Tool-loop threading (spec/20): a completed round serialises in OpenAI's wire shape — one
    # assistant message carrying the tool_calls array, then one `tool` message per result.
    st = Session(id="t")
    CompatBrain.record_tool_round(
        st, "checking", [ToolCall("c1", "system_status", {"x": 1})], {"c1": "noon"})
    assert st.history[0]["role"] == "assistant" and st.history[0]["content"] == "checking"
    assert st.history[0]["tool_calls"][0]["id"] == "c1"
    assert json.loads(st.history[0]["tool_calls"][0]["function"]["arguments"]) == {"x": 1}
    assert st.history[1] == {"role": "tool", "tool_call_id": "c1", "content": "noon"}

    # Effort is only sent where the card declares it — Groq's capabilities are empty, so asking
    # for effort there must NOT put an unsupported parameter on the wire.
    assert "reasoning_effort" not in CompatBrain("groq", model="m", api_key="x", effort="high") \
        ._kwargs(Session(id="t"), "q", [])
    assert CompatBrain("openai", model="m", api_key="x", effort="high") \
        ._kwargs(Session(id="t"), "q", [])["reasoning_effort"] == "high", \
        "OpenAI declares an effort capability, so it must be sent"

    # A local runner: no key needed, no usage request, temperature allowed.
    olla = CompatBrain("ollama", model="m", temperature=0.4)
    assert olla.local and olla.base_url == "http://localhost:11434/v1"
    assert olla._api_key == LOCAL_PLACEHOLDER_KEY, "a local runner must not demand a stored key"
    lk = olla._kwargs(Session(id="t"), "q", [])
    assert "stream_options" not in lk, "local servers are not all willing to report usage"
    assert lk["temperature"] == 0.4

    # Guard rails, each returning a mapped Error rather than raising.
    async def first(brain, session=None):
        async for ev in brain.converse(session or Session(id="t"), "q", []):
            return ev

    err = asyncio.run(first(CompatBrain("groq", model="m", api_key="x"),
                            Session(id="t", local_only=True)))
    assert isinstance(err, Error) and err.kind == "unavailable", err
    # ...but a LOCAL provider must serve a local_only session: that is the whole point of B2's
    # local half, and refusing here would make M2's privacy mode unimplementable.
    ok = asyncio.run(first(CompatBrain("ollama", model="m"), Session(id="t", local_only=True)))
    assert not (isinstance(ok, Error) and "local_only" in ok.detail), \
        "a local runner must accept a local_only session"
    assert asyncio.run(first(CompatBrain("groq", api_key="x"))).kind == "unknown", \
        "no model chosen must be reported, not sent as model=None"
    assert asyncio.run(first(CompatBrain("groq", model="m", api_key=None))).kind in ("auth", "unknown")

    # Client lifetime (spec/20). No network: every cost here is local CPU.
    assert ssl_context() is ssl_context(), "the CA bundle must be parsed once per process"
    first_client = groq._client_once()
    assert groq._client_once() is first_client, "the client must be built once and kept"
    t0 = time.perf_counter()
    CompatBrain("groq", model="m", api_key="x")._client_once()
    build_ms = (time.perf_counter() - t0) * 1000
    assert build_ms < 50, f"building the client took {build_ms:.0f} ms — CA bundle reloaded?"
    assert first_client.timeout.read >= 60, \
        f"custom client dropped the SDK read timeout: {first_client.timeout}"
    assert str(first_client.base_url).rstrip("/") == groq.base_url.rstrip("/")

    # Every catalogue provider on this wire must be constructible — that is what `adapter: true`
    # promises the settings window, and a card missing an api/endpoint would break it silently.
    from .providers import catalog, wire

    served = [p for p, c in catalog().items() if c.get("adapter") and wire(p) == "openai"]
    assert served, "no provider is wired to B2 — check `adapter` in settings.json"
    for pid in served:
        assert CompatBrain(pid, model="m", api_key="x").base_url, f"{pid}: no reachable base URL"

    print(f"selfcheck OK: {len(served)} providers on one adapter, tool translation drops `tier`, "
          "system-as-message, effort gated by capability, error mapping by type/status, "
          "client built once with the long read timeout intact")


def main() -> None:
    ap = argparse.ArgumentParser(description="Gemma B2 OpenAI-compatible adapter (spec/20)")
    ap.add_argument("provider", nargs="?", help="catalogue id: groq, openai, ollama, …")
    ap.add_argument("question", nargs="?", help="prompt to send")
    ap.add_argument("--model", default=None, help="model id (required for cloud providers)")
    ap.add_argument("--selfcheck", action="store_true", help="offline logic check, no network")
    args = ap.parse_args()

    if args.selfcheck:
        _selfcheck()
        return
    if not args.provider or not args.question:
        ap.error("provide a provider and a question, or --selfcheck")
    sys.exit(asyncio.run(_run(args.provider, args.question, args.model)))


if __name__ == "__main__":
    main()
